// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMFt-U3wO4ormaSZF3j9yWEdBISgmZTiY',
    appId: '1:1058666263748:web:cb9e04b86dc80e1c03c591',
    messagingSenderId: '1058666263748',
    projectId: 'consorcio-360-2c56d',
    authDomain: 'consorcio-360-2c56d.firebaseapp.com',
    storageBucket: 'consorcio-360-2c56d.firebasestorage.app',
    measurementId: 'G-ZP85NVD9RG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGtzha1Ekg0Lri5b8VU058rgLZu1JvsiA',
    appId: '1:1058666263748:android:d8d8f3f503d1191603c591',
    messagingSenderId: '1058666263748',
    projectId: 'consorcio-360-2c56d',
    storageBucket: 'consorcio-360-2c56d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7vv5a5HsfOu0m9tNYKNvX-3iwVcjfWjU',
    appId: '1:1058666263748:ios:9fd3f352783e736303c591',
    messagingSenderId: '1058666263748',
    projectId: 'consorcio-360-2c56d',
    storageBucket: 'consorcio-360-2c56d.firebasestorage.app',
    iosBundleId: 'com.example.consorcio360',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7vv5a5HsfOu0m9tNYKNvX-3iwVcjfWjU',
    appId: '1:1058666263748:ios:9fd3f352783e736303c591',
    messagingSenderId: '1058666263748',
    projectId: 'consorcio-360-2c56d',
    storageBucket: 'consorcio-360-2c56d.firebasestorage.app',
    iosBundleId: 'com.example.consorcio360',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMFt-U3wO4ormaSZF3j9yWEdBISgmZTiY',
    appId: '1:1058666263748:web:73c7fe87f6e4259c03c591',
    messagingSenderId: '1058666263748',
    projectId: 'consorcio-360-2c56d',
    authDomain: 'consorcio-360-2c56d.firebaseapp.com',
    storageBucket: 'consorcio-360-2c56d.firebasestorage.app',
    measurementId: 'G-PHEE885925',
  );

}